package com.rvlt.sfgpetclinic.bootstrap;

import com.rvlt.sfgpetclinic.model.*;
import com.rvlt.sfgpetclinic.services.OwnerService;
import com.rvlt.sfgpetclinic.services.PetTypeService;
import com.rvlt.sfgpetclinic.services.SpecialityService;
import com.rvlt.sfgpetclinic.services.VetService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.time.LocalDate;

// CommandLineRunner interface indicates this class's run method
// to be called when context is ready

@Component
public class DataLoader implements CommandLineRunner {

    private final OwnerService ownerService;
    private final VetService vetService;
    private final PetTypeService petTypeService;
    private final SpecialityService specialityService;

    public DataLoader(OwnerService ownerService, VetService vetService, PetTypeService petTypeService, SpecialityService specialityService) {
        this.ownerService = ownerService;
        this.vetService = vetService;
        this.petTypeService = petTypeService;
        this.specialityService = specialityService;
    }

    @Override
    public void run(String... args) throws Exception {

        int cnt = petTypeService.findAll().size();
        if (cnt == 0) loadData();

    }

    private void loadData() {
        loadPetsAndOwners();
        loadVets();
    }

    private void loadPetsAndOwners() {
        PetType dog = new PetType();
        dog.setName("DogType");
        PetType savedDogPetType = petTypeService.save(dog); // id generated by service

        PetType cat = new PetType();
        cat.setName("CatType");
        PetType savedCatPetType = petTypeService.save(cat); // id generated by service


        Owner owner1 = new Owner();
        owner1.setFirstName("Yoda");
        owner1.setLastName("Greenthing");
        owner1.setAddress("Dagoba Swamp");
        owner1.setCity("Dagoba City");
        owner1.setTelephone("1-800-do-or-do-not");
        ownerService.save(owner1);

        Pet pet1 = new Pet();
        pet1.setName("Pita");
        pet1.setPetType(savedDogPetType);
        pet1.setBirthDate(LocalDate.now());
        pet1.setOwner(owner1);
        owner1.getPets().add(pet1);


        Owner owner2 = new Owner();
        owner2.setFirstName("Luke");
        owner2.setLastName("Skywalker");
        owner2.setAddress("Renovated Jedi Temple");
        owner2.setCity("New Jedaya");
        owner2.setTelephone("1-800-join-the-light-side");
        ownerService.save(owner2);

        Pet pet2 = new Pet();
        pet2.setName("Chukaka");
        pet2.setPetType(savedCatPetType);
        pet2.setBirthDate(LocalDate.now());
        pet2.setOwner(owner2);
        owner2.getPets().add(pet2);


        System.out.println("Owners Loaded.");
    }

    private void loadVets() {
        Speciality radiology = new Speciality();
        radiology.setDescription("Radiology");
        Speciality savedRadiology = specialityService.save(radiology);

        Speciality surgery = new Speciality();
        surgery.setDescription("Surgery");
        Speciality savedSurgery = specialityService.save(surgery);

        Speciality dentistry = new Speciality();
        dentistry.setDescription("Dentistry");
        Speciality savedDentistry = specialityService.save(dentistry);


        Vet vet1 = new Vet();
        vet1.setFirstName("Vet");
        vet1.setLastName("Vader");
        vet1.getSpecialities().add(savedRadiology);
        vetService.save(vet1);

        Vet vet2 = new Vet();
        vet2.setFirstName("Vet");
        vet2.setLastName("Leah");
        vet2.getSpecialities().add(savedSurgery);
        vetService.save(vet2);


        System.out.println("Vets Loaded.");
    }
}
